// FrontENd/src/lib/components/BTEcard.svelte
<script>
    export let image;
    export let name;
    export let description;
</script>

<div class=" w-[380px] h-[500px] rounded-lg">
    <img src={image} class="rounded-lg w-[380px] h-[320px]"  alt="">
    <h2 class="text-xl  font-bold text-blue-900 mb-4 mt-3">
        {name}
      </h2>
      <p class="text-gray-600 leading-relaxed text-sm text-justify ">
        {description}
      </p>
</div>

// hearing-center-next/components/BTEcard.tsx
export default function BTEcard({
  image,
  name,
  description,
}: {
  image: string;
  name: string;
  description: string;
}) {
  return (
    <div className="w-[380px] h-[500px] rounded-lg">
      <img src={image} className="rounded-lg w-[380px] h-[320px]" alt="" />
      <h2 className="text-xl font-bold text-blue-900 mb-4 mt-3">{name}</h2>
      <p className="text-gray-600 leading-relaxed text-sm text-justify">
        {description}
      </p>
    </div>
  );
}
